import { useCallback, useEffect, useMemo, useState } from "react";
import { CalendarPlus, Clock, MapPin, Plus } from "lucide-react";
import { calendarApi } from "../services/calendar";
import type { CalendarEvent } from "../types";

export default function MobileCalendar() {
  const [cursor, setCursor] = useState(new Date());
  const [events, setEvents] = useState<CalendarEvent[]>([]);
  const [creating, setCreating] = useState(false);
  const [title, setTitle] = useState("");
  const dayStart = useMemo(() => { const value = new Date(cursor); value.setHours(0, 0, 0, 0); return value; }, [cursor]);
  const load = useCallback(async () => { const end = new Date(dayStart); end.setHours(23, 59, 59, 999); const result = await calendarApi.feed(dayStart.toISOString(), end.toISOString()).catch(() => null); setEvents((result?.events ?? []).sort((a, b) => +new Date(a.start) - +new Date(b.start))); }, [dayStart]);
  useEffect(() => { void load(); }, [load]);
  const create = async () => { if (!title.trim()) return; const start = new Date(dayStart); start.setHours(9, 0, 0, 0); const end = new Date(start.getTime() + 60 * 60 * 1000); const result = await calendarApi.create({ title: title.trim(), start: start.toISOString(), end: end.toISOString(), allDay: false, color: "#6366f1" }).catch(() => null); if (result) setEvents((list) => [...list, result.event].sort((a, b) => +new Date(a.start) - +new Date(b.start))); setTitle(""); setCreating(false); };
  return <div className="mx-auto max-w-md px-5 pb-7 pt-[max(1.5rem,env(safe-area-inset-top))]"><header className="mb-6 flex items-start justify-between"><div><p className="text-sm font-medium text-indigo-300">Keep the day clear</p><h1 className="mt-1 text-3xl font-bold text-white">Plan</h1></div><button type="button" onClick={() => setCreating(true)} className="flex h-11 w-11 items-center justify-center rounded-2xl bg-indigo-500 text-white"><Plus size={22} /></button></header><div className="mb-5 grid grid-cols-3 items-center rounded-2xl border border-white/10 bg-white/[.045] p-2 text-center"><button type="button" onClick={() => setCursor((date) => new Date(date.getFullYear(), date.getMonth(), date.getDate() - 1))} className="rounded-xl py-2 text-slate-300">‹</button><button type="button" onClick={() => setCursor(new Date())} className="rounded-xl py-2 text-sm font-semibold text-white">{cursor.toLocaleDateString(undefined, { month: "short", day: "numeric" })}</button><button type="button" onClick={() => setCursor((date) => new Date(date.getFullYear(), date.getMonth(), date.getDate() + 1))} className="rounded-xl py-2 text-slate-300">›</button></div>{creating && <form onSubmit={(event) => { event.preventDefault(); void create(); }} className="mb-4 rounded-2xl border border-indigo-400/30 bg-indigo-500/10 p-3"><input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Event title" className="w-full bg-transparent px-2 py-2 text-base text-white outline-none placeholder:text-slate-500" /><button className="mt-2 w-full rounded-xl bg-indigo-500 py-2.5 text-sm font-semibold text-white">Add at 09:00</button></form>}<div className="space-y-3">{events.length ? events.map((event) => <article key={event.id} className="rounded-2xl border border-white/10 bg-white/[.045] p-4"><div className="flex items-start gap-3"><span className="mt-1 h-3 w-3 rounded-full" style={{ backgroundColor: event.color || "#818cf8" }} /><div className="min-w-0 flex-1"><p className="font-semibold text-white">{event.title}</p><p className="mt-2 flex items-center gap-2 text-sm text-slate-400"><Clock size={15} />{event.allDay ? "All day" : new Date(event.start).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</p>{event.location && <p className="mt-1 flex items-center gap-2 text-sm text-slate-400"><MapPin size={15} />{event.location}</p>}</div></div></article>) : <div className="rounded-3xl border border-dashed border-white/15 px-5 py-12 text-center"><CalendarPlus className="mx-auto mb-3 text-indigo-300" size={28} /><p className="font-semibold text-white">Nothing scheduled</p><p className="mt-1 text-sm text-slate-400">Add an event or take the space back for yourself.</p></div>}</div></div>;
}
