import { useCallback, useEffect, useMemo, useState } from "react";
import { Check, ChevronDown, Circle, Plus, SlidersHorizontal } from "lucide-react";
import { tasksApi, STATUS_LABELS } from "../services/tasks";
import type { Task, TaskPriority, TaskStatus } from "../types";

const priorityStyle: Record<TaskPriority, string> = { HIGH: "bg-rose-400", MEDIUM: "bg-amber-400", LOW: "bg-sky-400" };

export default function MobileTasks() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [status, setStatus] = useState<"all" | TaskStatus>("all");
  const [draft, setDraft] = useState("");
  const [adding, setAdding] = useState(false);
  const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); const result = await tasksApi.list().catch(() => null); setTasks(result?.tasks ?? []); setLoading(false); }, []);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => tasks.filter((task) => status === "all" || task.status === status).sort((a, b) => Number(a.status === "DONE") - Number(b.status === "DONE") || +new Date(a.dueDate || "2999-01-01") - +new Date(b.dueDate || "2999-01-01")), [tasks, status]);
  const create = async () => { if (!draft.trim()) return; const result = await tasksApi.create({ title: draft.trim(), status: "TODO", priority: "MEDIUM" }).catch(() => null); if (result) setTasks((list) => [result.task, ...list]); setDraft(""); setAdding(false); };
  const toggle = async (task: Task) => { const next: TaskStatus = task.status === "DONE" ? "TODO" : "DONE"; setTasks((list) => list.map((item) => item.id === task.id ? { ...item, status: next } : item)); await tasksApi.update(task.id, { status: next }).catch(() => { void load(); }); };
  return <div className="mx-auto max-w-md px-5 pb-7 pt-[max(1.5rem,env(safe-area-inset-top))]"><header className="mb-6 flex items-center justify-between"><div><p className="text-sm font-medium text-indigo-300">Get it done</p><h1 className="mt-1 text-3xl font-bold text-white">Tasks</h1></div><button type="button" onClick={() => setAdding(true)} className="flex h-11 w-11 items-center justify-center rounded-2xl bg-indigo-500 text-white shadow-lg shadow-indigo-950/40"><Plus size={22} /></button></header><div className="mb-5 flex gap-2 overflow-x-auto pb-1">{(["all", "TODO", "IN_PROGRESS", "DONE"] as const).map((value) => <button key={value} type="button" onClick={() => setStatus(value)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-medium ${status === value ? "bg-indigo-500 text-white" : "bg-white/[.06] text-slate-300"}`}>{value === "all" ? "All" : STATUS_LABELS[value]}</button>)}</div>{adding && <form onSubmit={(event) => { event.preventDefault(); void create(); }} className="mb-4 rounded-2xl border border-indigo-400/30 bg-indigo-500/10 p-3"><input autoFocus value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="What needs doing?" className="w-full bg-transparent px-2 py-2 text-base text-white outline-none placeholder:text-slate-500" /><div className="mt-2 flex justify-end gap-2"><button type="button" onClick={() => setAdding(false)} className="rounded-xl px-3 py-2 text-sm text-slate-400">Cancel</button><button className="rounded-xl bg-indigo-500 px-4 py-2 text-sm font-semibold text-white">Add task</button></div></form>}<div className="space-y-2">{loading ? <div className="h-16 animate-pulse rounded-2xl bg-white/[.06]" /> : visible.length ? visible.map((task) => <article key={task.id} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[.045] p-4"><button type="button" onClick={() => void toggle(task)} className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full border ${task.status === "DONE" ? "border-emerald-400 bg-emerald-400 text-slate-950" : "border-slate-500 text-transparent"}`}><Check size={16} /></button><div className="min-w-0 flex-1"><p className={`truncate text-sm font-semibold ${task.status === "DONE" ? "text-slate-500 line-through" : "text-white"}`}>{task.title}</p><p className="mt-1 text-xs text-slate-400">{task.dueDate ? new Date(task.dueDate).toLocaleDateString() : "No deadline"}</p></div><span className={`h-2.5 w-2.5 rounded-full ${priorityStyle[task.priority]}`} /></article>) : <div className="rounded-2xl border border-dashed border-white/15 px-4 py-8 text-center text-sm text-slate-400">No tasks here. Your future self approves.</div>}</div></div>;
}
